--- #YAML:1.0
name:                Template-Process
version:             0.0004
abstract:            Process TT2 templates against data files
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Carp:                          0
    Class::Accessor:               0
    Getopt::Long:                  0
    Template:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adriano Ferreira <ferreira@cpan.org>
